import type { Product } from '../types'

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'primo-maxx',
    name: 'Primo Maxx / T-Nex',
    activeIngredient: 'Trinexapac-ethyl',
    manufacturer: 'Syngenta / Quali-Pro',
    description:
      'The most widely used PGR in turfgrass management. Inhibits gibberellin biosynthesis to reduce vertical growth, increase tillering, and improve turf density and color.',
    grassProfiles: [
      // Cool-season grasses
      { grassType: 'kentucky_bluegrass', mowingHeight: 'low', gddThreshold: 200, rateOzPer1000SqFt: 0.38 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'medium', gddThreshold: 250, rateOzPer1000SqFt: 0.38 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'high', gddThreshold: 300, rateOzPer1000SqFt: 0.44 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'low', gddThreshold: 200, rateOzPer1000SqFt: 0.38 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'medium', gddThreshold: 250, rateOzPer1000SqFt: 0.38 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'high', gddThreshold: 300, rateOzPer1000SqFt: 0.44 },
      { grassType: 'tall_fescue', mowingHeight: 'low', gddThreshold: 250, rateOzPer1000SqFt: 0.38 },
      { grassType: 'tall_fescue', mowingHeight: 'medium', gddThreshold: 300, rateOzPer1000SqFt: 0.44 },
      { grassType: 'tall_fescue', mowingHeight: 'high', gddThreshold: 350, rateOzPer1000SqFt: 0.44 },
      { grassType: 'fine_fescue', mowingHeight: 'low', gddThreshold: 200, rateOzPer1000SqFt: 0.38 },
      { grassType: 'fine_fescue', mowingHeight: 'medium', gddThreshold: 250, rateOzPer1000SqFt: 0.38 },
      { grassType: 'fine_fescue', mowingHeight: 'high', gddThreshold: 300, rateOzPer1000SqFt: 0.44 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'low', gddThreshold: 200, rateOzPer1000SqFt: 0.22 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'medium', gddThreshold: 250, rateOzPer1000SqFt: 0.30 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'high', gddThreshold: 300, rateOzPer1000SqFt: 0.38 },
      // Warm-season grasses
      { grassType: 'bermudagrass', mowingHeight: 'low', gddThreshold: 250, rateOzPer1000SqFt: 0.38 },
      { grassType: 'bermudagrass', mowingHeight: 'medium', gddThreshold: 300, rateOzPer1000SqFt: 0.44 },
      { grassType: 'bermudagrass', mowingHeight: 'high', gddThreshold: 350, rateOzPer1000SqFt: 0.44 },
      { grassType: 'zoysiagrass', mowingHeight: 'low', gddThreshold: 250, rateOzPer1000SqFt: 0.38 },
      { grassType: 'zoysiagrass', mowingHeight: 'medium', gddThreshold: 300, rateOzPer1000SqFt: 0.44 },
      { grassType: 'zoysiagrass', mowingHeight: 'high', gddThreshold: 350, rateOzPer1000SqFt: 0.44 },
      { grassType: 'st_augustinegrass', mowingHeight: 'medium', gddThreshold: 300, rateOzPer1000SqFt: 0.44 },
      { grassType: 'st_augustinegrass', mowingHeight: 'high', gddThreshold: 350, rateOzPer1000SqFt: 0.44 },
      { grassType: 'buffalograss', mowingHeight: 'medium', gddThreshold: 300, rateOzPer1000SqFt: 0.38 },
      { grassType: 'buffalograss', mowingHeight: 'high', gddThreshold: 350, rateOzPer1000SqFt: 0.44 },
      { grassType: 'centipedegrass', mowingHeight: 'medium', gddThreshold: 300, rateOzPer1000SqFt: 0.38 },
      { grassType: 'centipedegrass', mowingHeight: 'high', gddThreshold: 350, rateOzPer1000SqFt: 0.44 },
    ],
  },
  {
    id: 'anuew',
    name: 'Anuew',
    activeIngredient: 'Prohexadione calcium',
    manufacturer: 'Nufarm',
    description:
      'A newer PGR with a shorter regulation window. Offers quick suppression with faster recovery, making it ideal for situations where flexibility is needed.',
    grassProfiles: [
      { grassType: 'kentucky_bluegrass', mowingHeight: 'low', gddThreshold: 175, rateOzPer1000SqFt: 0.28 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'medium', gddThreshold: 200, rateOzPer1000SqFt: 0.28 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'high', gddThreshold: 225, rateOzPer1000SqFt: 0.34 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'low', gddThreshold: 175, rateOzPer1000SqFt: 0.28 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'medium', gddThreshold: 200, rateOzPer1000SqFt: 0.28 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'high', gddThreshold: 225, rateOzPer1000SqFt: 0.34 },
      { grassType: 'tall_fescue', mowingHeight: 'low', gddThreshold: 200, rateOzPer1000SqFt: 0.28 },
      { grassType: 'tall_fescue', mowingHeight: 'medium', gddThreshold: 225, rateOzPer1000SqFt: 0.34 },
      { grassType: 'tall_fescue', mowingHeight: 'high', gddThreshold: 275, rateOzPer1000SqFt: 0.34 },
      { grassType: 'fine_fescue', mowingHeight: 'low', gddThreshold: 175, rateOzPer1000SqFt: 0.28 },
      { grassType: 'fine_fescue', mowingHeight: 'medium', gddThreshold: 200, rateOzPer1000SqFt: 0.28 },
      { grassType: 'fine_fescue', mowingHeight: 'high', gddThreshold: 225, rateOzPer1000SqFt: 0.34 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'low', gddThreshold: 150, rateOzPer1000SqFt: 0.18 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'medium', gddThreshold: 175, rateOzPer1000SqFt: 0.22 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'high', gddThreshold: 200, rateOzPer1000SqFt: 0.28 },
      { grassType: 'bermudagrass', mowingHeight: 'low', gddThreshold: 200, rateOzPer1000SqFt: 0.28 },
      { grassType: 'bermudagrass', mowingHeight: 'medium', gddThreshold: 250, rateOzPer1000SqFt: 0.34 },
      { grassType: 'bermudagrass', mowingHeight: 'high', gddThreshold: 275, rateOzPer1000SqFt: 0.34 },
      { grassType: 'zoysiagrass', mowingHeight: 'low', gddThreshold: 200, rateOzPer1000SqFt: 0.28 },
      { grassType: 'zoysiagrass', mowingHeight: 'medium', gddThreshold: 250, rateOzPer1000SqFt: 0.34 },
      { grassType: 'zoysiagrass', mowingHeight: 'high', gddThreshold: 275, rateOzPer1000SqFt: 0.34 },
    ],
  },
  {
    id: 'cutless-mec',
    name: 'Cutless MEC',
    activeIngredient: 'Flurprimidol',
    manufacturer: 'SePRO',
    description:
      'A long-lasting PGR that provides extended growth regulation. Particularly effective on warm-season grasses and in landscape bed applications for ornamental growth control.',
    grassProfiles: [
      { grassType: 'kentucky_bluegrass', mowingHeight: 'low', gddThreshold: 300, rateOzPer1000SqFt: 0.50 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'medium', gddThreshold: 350, rateOzPer1000SqFt: 0.50 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'high', gddThreshold: 400, rateOzPer1000SqFt: 0.67 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'low', gddThreshold: 300, rateOzPer1000SqFt: 0.50 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'medium', gddThreshold: 350, rateOzPer1000SqFt: 0.50 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'high', gddThreshold: 400, rateOzPer1000SqFt: 0.67 },
      { grassType: 'tall_fescue', mowingHeight: 'medium', gddThreshold: 350, rateOzPer1000SqFt: 0.50 },
      { grassType: 'tall_fescue', mowingHeight: 'high', gddThreshold: 400, rateOzPer1000SqFt: 0.67 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'low', gddThreshold: 250, rateOzPer1000SqFt: 0.33 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'medium', gddThreshold: 300, rateOzPer1000SqFt: 0.50 },
      { grassType: 'bermudagrass', mowingHeight: 'low', gddThreshold: 350, rateOzPer1000SqFt: 0.50 },
      { grassType: 'bermudagrass', mowingHeight: 'medium', gddThreshold: 400, rateOzPer1000SqFt: 0.67 },
      { grassType: 'bermudagrass', mowingHeight: 'high', gddThreshold: 450, rateOzPer1000SqFt: 0.67 },
      { grassType: 'zoysiagrass', mowingHeight: 'low', gddThreshold: 350, rateOzPer1000SqFt: 0.50 },
      { grassType: 'zoysiagrass', mowingHeight: 'medium', gddThreshold: 400, rateOzPer1000SqFt: 0.67 },
      { grassType: 'zoysiagrass', mowingHeight: 'high', gddThreshold: 450, rateOzPer1000SqFt: 0.67 },
      { grassType: 'st_augustinegrass', mowingHeight: 'medium', gddThreshold: 400, rateOzPer1000SqFt: 0.67 },
      { grassType: 'st_augustinegrass', mowingHeight: 'high', gddThreshold: 450, rateOzPer1000SqFt: 0.67 },
    ],
  },
  {
    id: 'trimmit',
    name: 'Trimmit / Pac Man',
    activeIngredient: 'Paclobutrazol',
    manufacturer: 'Syngenta / Quali-Pro',
    description:
      'A soil-active PGR that is taken up through the roots. Provides long-lasting growth suppression and is commonly used in tank mixes with trinexapac-ethyl for enhanced regulation.',
    grassProfiles: [
      { grassType: 'kentucky_bluegrass', mowingHeight: 'low', gddThreshold: 350, rateOzPer1000SqFt: 0.38 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'medium', gddThreshold: 400, rateOzPer1000SqFt: 0.38 },
      { grassType: 'kentucky_bluegrass', mowingHeight: 'high', gddThreshold: 450, rateOzPer1000SqFt: 0.44 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'low', gddThreshold: 350, rateOzPer1000SqFt: 0.38 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'medium', gddThreshold: 400, rateOzPer1000SqFt: 0.38 },
      { grassType: 'perennial_ryegrass', mowingHeight: 'high', gddThreshold: 450, rateOzPer1000SqFt: 0.44 },
      { grassType: 'tall_fescue', mowingHeight: 'medium', gddThreshold: 400, rateOzPer1000SqFt: 0.38 },
      { grassType: 'tall_fescue', mowingHeight: 'high', gddThreshold: 450, rateOzPer1000SqFt: 0.44 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'low', gddThreshold: 300, rateOzPer1000SqFt: 0.22 },
      { grassType: 'creeping_bentgrass', mowingHeight: 'medium', gddThreshold: 350, rateOzPer1000SqFt: 0.30 },
      { grassType: 'bermudagrass', mowingHeight: 'low', gddThreshold: 400, rateOzPer1000SqFt: 0.38 },
      { grassType: 'bermudagrass', mowingHeight: 'medium', gddThreshold: 450, rateOzPer1000SqFt: 0.44 },
      { grassType: 'bermudagrass', mowingHeight: 'high', gddThreshold: 500, rateOzPer1000SqFt: 0.44 },
      { grassType: 'zoysiagrass', mowingHeight: 'low', gddThreshold: 400, rateOzPer1000SqFt: 0.38 },
      { grassType: 'zoysiagrass', mowingHeight: 'medium', gddThreshold: 450, rateOzPer1000SqFt: 0.44 },
      { grassType: 'zoysiagrass', mowingHeight: 'high', gddThreshold: 500, rateOzPer1000SqFt: 0.44 },
    ],
  },
]
